---
- name: Converge
  hosts: all
  become: yes
  become_user: root
  become_method: doas
  vars:
    newsyslog_extra_rules:
      - name: /tmp/garbage
        owner: root
        group: wheel
        mode: 644
        count: 3
        size: 1
  tasks:
    - name: "Include tleguern.newsyslog"
      include_role:
        name: "tleguern.newsyslog"
